version: '2'
services:
    minibook-app:
        image: minibook
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://minibook-postgresql:5432/minibook
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    minibook-postgresql:
        extends:
            file: postgresql.yml
            service: minibook-postgresql
